databases:
  - name: digital-card-db
    plan: free
    databaseName: digital_card

services:
  - type: web
    name: digital-card-api
    runtime: docker
    plan: free
    healthCheckPath: /graphql?query=%7B__typename%7D
    envVars:
      - key: NODE_ENV
        value: production
      - key: SEED_ON_START
        value: 'true'
      - key: DATABASE_URL
        fromDatabase:
          name: digital-card-db
          property: connectionString
